### ISSUE TITLE
Questions about the use of test datset sets

### ISSUE THREAD

**Issue by thatc** [ChineseboyLuo/CFM#1]
Thanks for your wonderful work.
Could you please specify how many frames were used for each video experiment during the testing phase? Were all frames of a video used, or was a fixed number of frames (n frames) used?

Thanks again for your work, it helps me a lot!

**Comment by LoveSiameseCat** [comment]
Thank you for your interst in our work. The official evaluation uses 300 frames per video, but we found use 50 frames per video can get similar results. BTW, we sample these frames accordding to the sampling interval, which is calculated by video length//50.  Hope it can address your problem.

**Comment by thatc** [comment]
Thanks for the reply, it was very helpful!
